-- Base de analitica para una base multimall que aun no tiene analytics_events.
-- Ejecutar antes de mall_operations_observability_20260913.sql.

begin;

do $$
begin
    if not exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'malls'
    ) then
        raise exception 'Falta la tabla public.malls. Abre el proyecto de Supabase que usa el mall.';
    end if;
end;
$$;

create table if not exists public.analytics_sessions (
    id uuid primary key,
    mall_id uuid not null references public.malls(id),
    auth_user_id uuid references auth.users(id) on delete set null,
    visitor_role text not null default 'guest'
        check (visitor_role in ('guest', 'member', 'tenant', 'admin', 'authenticated')),
    device_class text not null default 'desktop'
        check (device_class in ('mobile', 'tablet', 'desktop')),
    started_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
    id bigint generated by default as identity primary key,
    mall_id uuid not null references public.malls(id),
    client_event_id uuid not null unique,
    session_id uuid not null references public.analytics_sessions(id) on delete cascade,
    auth_user_id uuid references auth.users(id) on delete set null,
    visitor_role text not null
        check (visitor_role in ('guest', 'member', 'tenant', 'admin', 'authenticated')),
    event_name text not null check (event_name in (
        'session_started', 'mall_entered', 'search_opened', 'search_submitted',
        'search_result_clicked', 'route_requested', 'store_attention_qualified',
        'store_attention_ended', 'store_opened', 'product_viewed', 'contact_clicked',
        'message_sent', 'login_succeeded', 'zone_entered', 'maze_started',
        'maze_completed', 'maze_exited', 'assistant_question_sent', 'feedback_submitted'
    )),
    occurred_at timestamptz not null default now(),
    store_id text references public.stores(id) on delete set null,
    local_code text,
    product_id text,
    search_term text,
    channel text,
    source text,
    item_label text,
    duration_ms integer,
    result_count integer,
    device_class text not null default 'desktop'
        check (device_class in ('mobile', 'tablet', 'desktop')),
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists analytics_sessions_mall_seen_idx
    on public.analytics_sessions (mall_id, last_seen_at desc);
create index if not exists analytics_events_mall_time_idx
    on public.analytics_events (mall_id, occurred_at desc);
create index if not exists analytics_events_mall_event_time_idx
    on public.analytics_events (mall_id, event_name, occurred_at desc);
create index if not exists analytics_events_store_time_idx
    on public.analytics_events (store_id, occurred_at desc);
create index if not exists analytics_events_session_time_idx
    on public.analytics_events (session_id, occurred_at desc);

alter table public.analytics_sessions enable row level security;
alter table public.analytics_events enable row level security;
revoke all on public.analytics_sessions from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;

commit;
