-- Mall Creaciones - analitica privada y agregados autorizados.
-- Ejecutar una vez en Supabase SQL Editor. El script es repetible.

begin;

create table if not exists public.analytics_sessions (
    id uuid primary key,
    auth_user_id uuid references auth.users(id) on delete set null,
    visitor_role text not null default 'guest'
        check (visitor_role in ('guest', 'member', 'tenant', 'admin', 'authenticated')),
    device_class text not null default 'desktop'
        check (device_class in ('mobile', 'tablet', 'desktop')),
    started_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
    id bigint generated by default as identity primary key,
    client_event_id uuid not null unique,
    session_id uuid not null references public.analytics_sessions(id) on delete cascade,
    auth_user_id uuid references auth.users(id) on delete set null,
    visitor_role text not null
        check (visitor_role in ('guest', 'member', 'tenant', 'admin', 'authenticated')),
    event_name text not null
        check (event_name in (
            'session_started',
            'mall_entered',
            'search_opened',
            'search_submitted',
            'search_result_clicked',
            'route_requested',
            'store_attention_qualified',
            'store_attention_ended',
            'store_opened',
            'product_viewed',
            'contact_clicked',
            'message_sent',
            'login_succeeded'
        )),
    occurred_at timestamptz not null default now(),
    store_id text references public.stores(id) on delete set null,
    local_code text,
    -- El proyecto ha usado UUID y bigint para store_products.id en distintas
    -- etapas. Analitica lo conserva como identificador opaco y lo valida en RPC.
    product_id text,
    search_term text,
    channel text,
    source text,
    item_label text,
    duration_ms integer,
    result_count integer,
    device_class text not null default 'desktop'
        check (device_class in ('mobile', 'tablet', 'desktop')),
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_occurred_at_idx
on public.analytics_events (occurred_at desc);

create index if not exists analytics_events_store_time_idx
on public.analytics_events (store_id, occurred_at desc);

create index if not exists analytics_events_session_time_idx
on public.analytics_events (session_id, occurred_at desc);

create index if not exists analytics_events_name_time_idx
on public.analytics_events (event_name, occurred_at desc);

create index if not exists analytics_events_product_time_idx
on public.analytics_events (product_id, occurred_at desc)
where product_id is not null;

alter table public.analytics_sessions enable row level security;
alter table public.analytics_events enable row level security;

-- Compatibilidad si una version anterior alcanzo a crear la tabla con bigint.
alter table public.analytics_events
    drop constraint if exists analytics_events_product_id_fkey;
alter table public.analytics_events
    alter column product_id type text using product_id::text;

-- No se crean politicas de lectura o escritura directa. Toda operacion pasa por
-- funciones SECURITY DEFINER con validacion y autorizacion explicitas.
revoke all on public.analytics_sessions from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;

drop function if exists public.record_analytics_event(
    uuid, uuid, text, text, bigint, text, text, text, text, integer, integer, text
);

create or replace function public.record_analytics_event(
    p_client_event_id uuid,
    p_session_id uuid,
    p_event_name text,
    p_store_code text default null,
    p_product_id text default null,
    p_search_term text default null,
    p_channel text default null,
    p_source text default null,
    p_item_label text default null,
    p_duration_ms integer default null,
    p_result_count integer default null,
    p_device_class text default 'desktop'
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    resolved_store_id text;
    resolved_local_code text;
    resolved_product_id text;
    resolved_role text := 'guest';
    clean_event_name text := lower(trim(coalesce(p_event_name, '')));
    clean_search_term text;
    clean_channel text;
    clean_source text;
    clean_item_label text;
    clean_device_class text := lower(trim(coalesce(p_device_class, 'desktop')));
    clean_duration_ms integer;
    clean_result_count integer;
begin
    if p_client_event_id is null or p_session_id is null then
        return false;
    end if;

    if clean_event_name not in (
        'session_started',
        'mall_entered',
        'search_opened',
        'search_submitted',
        'search_result_clicked',
        'route_requested',
        'store_attention_qualified',
        'store_attention_ended',
        'store_opened',
        'product_viewed',
        'contact_clicked',
        'message_sent',
        'login_succeeded'
    ) then
        return false;
    end if;

    if clean_device_class not in ('mobile', 'tablet', 'desktop') then
        clean_device_class := 'desktop';
    end if;

    if auth.uid() is not null then
        resolved_role := 'authenticated';
        if public.is_mall_admin() then
            resolved_role := 'admin';
        elsif exists (
            select 1 from public.stores s where s.owner_id = auth.uid()
        ) then
            resolved_role := 'tenant';
        elsif exists (
            select 1 from public.mall_members mm where mm.auth_user_id = auth.uid()
        ) then
            resolved_role := 'member';
        end if;
    end if;

    -- Limite defensivo por sesion. No sustituye el rate limiting del gateway,
    -- pero evita rafagas accidentales del cliente.
    if (
        select count(*)
        from public.analytics_events e
        where e.session_id = p_session_id
          and e.occurred_at >= now() - interval '1 minute'
    ) >= 90 then
        return false;
    end if;

    if nullif(trim(coalesce(p_store_code, '')), '') is not null then
        select s.id, s.local_code
        into resolved_store_id, resolved_local_code
        from public.stores s
        where upper(replace(trim(s.id), '-', '')) = upper(replace(trim(p_store_code), '-', ''))
           or upper(replace(trim(s.local_code), '-', '')) = upper(replace(trim(p_store_code), '-', ''))
        order by case
            when upper(replace(trim(s.local_code), '-', '')) = upper(replace(trim(p_store_code), '-', '')) then 0
            else 1
        end
        limit 1;
    end if;

    if p_product_id is not null and exists (
        select 1
        from public.store_products sp
        where sp.id::text = p_product_id
          and (
              resolved_store_id is null
              or upper(replace(trim(coalesce(sp.local_code, '')), '-', ''))
                 = upper(replace(trim(coalesce(resolved_local_code, '')), '-', ''))
          )
    ) then
        resolved_product_id := p_product_id;
    end if;

    clean_search_term := left(
        regexp_replace(lower(trim(coalesce(p_search_term, ''))), '\s+', ' ', 'g'),
        80
    );
    if clean_search_term = ''
       or clean_search_term like '%@%'
       or clean_search_term ~ '(\+?[0-9][[:space:]().-]*){7,}' then
        clean_search_term := null;
    end if;

    clean_channel := nullif(left(lower(trim(coalesce(p_channel, ''))), 24), '');
    if clean_channel is not null
       and clean_channel not in ('email', 'whatsapp', 'telegram', 'form', 'social', 'catalog', 'map') then
        clean_channel := null;
    end if;

    clean_source := nullif(left(lower(trim(coalesce(p_source, ''))), 40), '');
    clean_item_label := nullif(left(trim(coalesce(p_item_label, '')), 120), '');
    clean_duration_ms := case
        when p_duration_ms is null then null
        else least(600000, greatest(0, p_duration_ms))
    end;
    clean_result_count := case
        when p_result_count is null then null
        else least(500, greatest(0, p_result_count))
    end;

    insert into public.analytics_sessions (
        id,
        auth_user_id,
        visitor_role,
        device_class,
        started_at,
        last_seen_at
    )
    values (
        p_session_id,
        auth.uid(),
        resolved_role,
        clean_device_class,
        now(),
        now()
    )
    on conflict (id) do update
    set auth_user_id = coalesce(excluded.auth_user_id, analytics_sessions.auth_user_id),
        visitor_role = excluded.visitor_role,
        device_class = excluded.device_class,
        last_seen_at = now();

    insert into public.analytics_events (
        client_event_id,
        session_id,
        auth_user_id,
        visitor_role,
        event_name,
        store_id,
        local_code,
        product_id,
        search_term,
        channel,
        source,
        item_label,
        duration_ms,
        result_count,
        device_class,
        metadata
    )
    values (
        p_client_event_id,
        p_session_id,
        auth.uid(),
        resolved_role,
        clean_event_name,
        resolved_store_id,
        resolved_local_code,
        resolved_product_id,
        clean_search_term,
        clean_channel,
        clean_source,
        clean_item_label,
        clean_duration_ms,
        clean_result_count,
        clean_device_class,
        jsonb_strip_nulls(jsonb_build_object(
            'duration_bucket',
            case
                when clean_duration_ms is null then null
                when clean_duration_ms <= 5000 then '3-5s'
                when clean_duration_ms <= 10000 then '6-10s'
                when clean_duration_ms <= 20000 then '11-20s'
                else '20s+'
            end
        ))
    )
    on conflict (client_event_id) do nothing;

    return true;
end;
$$;

revoke all on function public.record_analytics_event(
    uuid, uuid, text, text, text, text, text, text, text, integer, integer, text
) from public;
grant execute on function public.record_analytics_event(
    uuid, uuid, text, text, text, text, text, text, text, integer, integer, text
) to anon, authenticated;

create or replace function public.get_store_analytics(
    p_store_id text,
    p_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    selected_store public.stores%rowtype;
    days_count integer := least(90, greatest(1, coalesce(p_days, 30)));
    range_start timestamptz;
    summary jsonb;
    daily_rows jsonb;
    top_products jsonb;
    top_searches jsonb;
begin
    if auth.uid() is null then
        raise exception 'Authentication required' using errcode = '42501';
    end if;

    select s.*
    into selected_store
    from public.stores s
    where upper(replace(trim(s.id), '-', '')) = upper(replace(trim(p_store_id), '-', ''))
       or upper(replace(trim(s.local_code), '-', '')) = upper(replace(trim(p_store_id), '-', ''))
    limit 1;

    if selected_store.id is null then
        raise exception 'Store not found' using errcode = 'P0002';
    end if;

    if not public.is_mall_admin() and selected_store.owner_id is distinct from auth.uid() then
        raise exception 'Not authorized for this store' using errcode = '42501';
    end if;

    range_start := date_trunc('day', now()) - make_interval(days => days_count - 1);

    select jsonb_build_object(
        'unique_visitors', count(distinct e.session_id),
        'attention_count', count(*) filter (where e.event_name = 'store_attention_qualified'),
        'attention_unique', count(distinct e.session_id) filter (where e.event_name = 'store_attention_qualified'),
        'store_opens', count(*) filter (where e.event_name = 'store_opened'),
        'product_views', count(*) filter (where e.event_name = 'product_viewed'),
        'contact_actions', count(*) filter (where e.event_name in ('contact_clicked', 'message_sent')),
        'messages_sent', count(*) filter (where e.event_name = 'message_sent'),
        'route_requests', count(*) filter (where e.event_name = 'route_requested'),
        'average_attention_seconds', coalesce(round(
            avg(e.duration_ms) filter (where e.event_name = 'store_attention_ended') / 1000.0,
            1
        ), 0)
    )
    into summary
    from public.analytics_events e
    where e.store_id = selected_store.id
      and e.occurred_at >= range_start
      and e.visitor_role in ('guest', 'member', 'authenticated');

    summary := summary || jsonb_build_object(
        'attention_without_action',
        (
            select count(*)
            from public.analytics_events attention
            where attention.store_id = selected_store.id
              and attention.event_name = 'store_attention_qualified'
              and attention.occurred_at >= range_start
              and attention.visitor_role in ('guest', 'member', 'authenticated')
              and not exists (
                  select 1
                  from public.analytics_events action
                  where action.store_id = attention.store_id
                    and action.session_id = attention.session_id
                    and action.event_name in ('store_opened', 'product_viewed', 'contact_clicked', 'message_sent')
                    and action.occurred_at between attention.occurred_at and attention.occurred_at + interval '30 minutes'
              )
        )
    );

    select coalesce(jsonb_agg(
        jsonb_build_object(
            'day', series.day::date,
            'unique_visitors', coalesce(metrics.unique_visitors, 0),
            'attention', coalesce(metrics.attention, 0),
            'store_opens', coalesce(metrics.store_opens, 0),
            'product_views', coalesce(metrics.product_views, 0),
            'contacts', coalesce(metrics.contacts, 0)
        )
        order by series.day
    ), '[]'::jsonb)
    into daily_rows
    from generate_series(
        date_trunc('day', now()) - make_interval(days => days_count - 1),
        date_trunc('day', now()),
        interval '1 day'
    ) as series(day)
    left join lateral (
        select
            count(distinct e.session_id) as unique_visitors,
            count(*) filter (where e.event_name = 'store_attention_qualified') as attention,
            count(*) filter (where e.event_name = 'store_opened') as store_opens,
            count(*) filter (where e.event_name = 'product_viewed') as product_views,
            count(*) filter (where e.event_name in ('contact_clicked', 'message_sent')) as contacts
        from public.analytics_events e
        where e.store_id = selected_store.id
          and e.occurred_at >= series.day
          and e.occurred_at < series.day + interval '1 day'
          and e.visitor_role in ('guest', 'member', 'authenticated')
    ) metrics on true;

    select coalesce(jsonb_agg(row_data order by view_count desc, product_name), '[]'::jsonb)
    into top_products
    from (
        select
            coalesce(sp.name, e.item_label, 'Producto') as product_name,
            count(*) as view_count
        from public.analytics_events e
        left join public.store_products sp on sp.id::text = e.product_id
        where e.store_id = selected_store.id
          and e.event_name = 'product_viewed'
          and e.occurred_at >= range_start
          and e.visitor_role in ('guest', 'member', 'authenticated')
        group by coalesce(sp.name, e.item_label, 'Producto')
        order by count(*) desc
        limit 8
    ) row_data;

    select coalesce(jsonb_agg(row_data order by click_count desc, search_term), '[]'::jsonb)
    into top_searches
    from (
        select e.search_term, count(*) as click_count
        from public.analytics_events e
        where e.store_id = selected_store.id
          and e.event_name = 'search_result_clicked'
          and e.search_term is not null
          and e.occurred_at >= range_start
          and e.visitor_role in ('guest', 'member', 'authenticated')
        group by e.search_term
        order by count(*) desc
        limit 8
    ) row_data;

    return jsonb_build_object(
        'store', jsonb_build_object(
            'id', selected_store.id,
            'local_code', selected_store.local_code,
            'name', selected_store.name
        ),
        'days', days_count,
        'summary', summary,
        'daily', daily_rows,
        'top_products', top_products,
        'top_searches', top_searches
    );
end;
$$;

revoke all on function public.get_store_analytics(text, integer) from public;
grant execute on function public.get_store_analytics(text, integer) to authenticated;

create or replace function public.get_mall_analytics(
    p_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    days_count integer := least(90, greatest(1, coalesce(p_days, 30)));
    range_start timestamptz;
    summary jsonb;
    daily_rows jsonb;
    top_stores jsonb;
    missed_searches jsonb;
begin
    if auth.uid() is null or not public.is_mall_admin() then
        raise exception 'Administrator access required' using errcode = '42501';
    end if;

    range_start := date_trunc('day', now()) - make_interval(days => days_count - 1);

    select jsonb_build_object(
        'unique_visitors', count(distinct e.session_id),
        'mall_entries', count(*) filter (where e.event_name = 'mall_entered'),
        'searches', count(*) filter (where e.event_name = 'search_submitted'),
        'searches_without_results', count(*) filter (
            where e.event_name = 'search_submitted' and coalesce(e.result_count, 0) = 0
        ),
        'attention_count', count(*) filter (where e.event_name = 'store_attention_qualified'),
        'store_opens', count(*) filter (where e.event_name = 'store_opened'),
        'product_views', count(*) filter (where e.event_name = 'product_viewed'),
        'contact_actions', count(*) filter (where e.event_name in ('contact_clicked', 'message_sent')),
        'route_requests', count(*) filter (where e.event_name = 'route_requested')
    )
    into summary
    from public.analytics_events e
    where e.occurred_at >= range_start
      and e.visitor_role in ('guest', 'member', 'authenticated');

    select coalesce(jsonb_agg(
        jsonb_build_object(
            'day', series.day::date,
            'unique_visitors', coalesce(metrics.unique_visitors, 0),
            'mall_entries', coalesce(metrics.mall_entries, 0),
            'attention', coalesce(metrics.attention, 0),
            'store_opens', coalesce(metrics.store_opens, 0),
            'contacts', coalesce(metrics.contacts, 0)
        )
        order by series.day
    ), '[]'::jsonb)
    into daily_rows
    from generate_series(
        date_trunc('day', now()) - make_interval(days => days_count - 1),
        date_trunc('day', now()),
        interval '1 day'
    ) as series(day)
    left join lateral (
        select
            count(distinct e.session_id) as unique_visitors,
            count(*) filter (where e.event_name = 'mall_entered') as mall_entries,
            count(*) filter (where e.event_name = 'store_attention_qualified') as attention,
            count(*) filter (where e.event_name = 'store_opened') as store_opens,
            count(*) filter (where e.event_name in ('contact_clicked', 'message_sent')) as contacts
        from public.analytics_events e
        where e.occurred_at >= series.day
          and e.occurred_at < series.day + interval '1 day'
          and e.visitor_role in ('guest', 'member', 'authenticated')
    ) metrics on true;

    select coalesce(jsonb_agg(row_data order by activity_score desc, local_code), '[]'::jsonb)
    into top_stores
    from (
        select
            s.id as store_id,
            s.local_code,
            s.name,
            count(distinct e.session_id) as unique_visitors,
            count(*) filter (where e.event_name = 'store_attention_qualified') as attention,
            count(*) filter (where e.event_name = 'store_opened') as store_opens,
            count(*) filter (where e.event_name in ('contact_clicked', 'message_sent')) as contacts,
            (
                count(*) filter (where e.event_name = 'store_attention_qualified')
                + 2 * count(*) filter (where e.event_name = 'store_opened')
                + 3 * count(*) filter (where e.event_name = 'product_viewed')
                + 8 * count(*) filter (where e.event_name in ('contact_clicked', 'message_sent'))
            ) as activity_score
        from public.stores s
        join public.analytics_events e on e.store_id = s.id
        where e.occurred_at >= range_start
          and e.visitor_role in ('guest', 'member', 'authenticated')
        group by s.id, s.local_code, s.name
        order by activity_score desc
        limit 10
    ) row_data;

    select coalesce(jsonb_agg(row_data order by search_count desc, search_term), '[]'::jsonb)
    into missed_searches
    from (
        select e.search_term, count(*) as search_count
        from public.analytics_events e
        where e.event_name = 'search_submitted'
          and e.result_count = 0
          and e.search_term is not null
          and e.occurred_at >= range_start
          and e.visitor_role in ('guest', 'member', 'authenticated')
        group by e.search_term
        order by count(*) desc
        limit 10
    ) row_data;

    return jsonb_build_object(
        'days', days_count,
        'summary', summary,
        'daily', daily_rows,
        'top_stores', top_stores,
        'searches_without_results', missed_searches
    );
end;
$$;

revoke all on function public.get_mall_analytics(integer) from public;
grant execute on function public.get_mall_analytics(integer) to authenticated;

create or replace function public.purge_old_analytics_events(
    p_retention_days integer default 90
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    deleted_count integer;
    retention_days integer := least(365, greatest(30, coalesce(p_retention_days, 90)));
begin
    if auth.uid() is null or not public.is_mall_admin() then
        raise exception 'Administrator access required' using errcode = '42501';
    end if;

    delete from public.analytics_events
    where occurred_at < now() - make_interval(days => retention_days);
    get diagnostics deleted_count = row_count;

    delete from public.analytics_sessions s
    where s.last_seen_at < now() - make_interval(days => retention_days)
      and not exists (
          select 1 from public.analytics_events e where e.session_id = s.id
      );

    return deleted_count;
end;
$$;

revoke all on function public.purge_old_analytics_events(integer) from public;
grant execute on function public.purge_old_analytics_events(integer) to authenticated;

commit;
