begin;

-- Configuración única del asistente que atiende el mesón de informaciones.
create table if not exists public.mall_assistant_settings (
    id smallint primary key default 1 check (id = 1),
    assistant_id text not null default 'main-information-assistant',
    physical_location text not null default 'Mesón principal de informaciones',
    object_key text not null default 'information-desk-main',
    position_x double precision not null default -17,
    position_y double precision not null default 2,
    position_z double precision not null default 0,
    rotation_y double precision not null default 1.5707963267948966,
    enabled boolean not null default true,
    assistant_name text not null default 'Asistente del Mall',
    greeting text not null default 'Hola. Soy el asistente del Mall Emprendimientos. ¿Qué información necesitas?',
    mall_brief text not null default '',
    handoff_message text not null default 'Si no encontraste la información que buscas, puedes dejar un reclamo o sugerencia para que la administración del mall lo revise.',
    faq jsonb not null default '[]'::jsonb check (jsonb_typeof(faq) = 'array'),
    max_turns integer not null default 4 check (max_turns between 1 and 6),
    question_max_chars integer not null default 300 check (question_max_chars between 80 and 500),
    answer_max_words integer not null default 80 check (answer_max_words between 30 and 120),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.mall_assistant_settings
    add column if not exists assistant_id text not null default 'main-information-assistant',
    add column if not exists physical_location text not null default 'Mesón principal de informaciones',
    add column if not exists object_key text not null default 'information-desk-main',
    add column if not exists position_x double precision not null default -17,
    add column if not exists position_y double precision not null default 2,
    add column if not exists position_z double precision not null default 0,
    add column if not exists rotation_y double precision not null default 1.5707963267948966;

create table if not exists public.mall_assistant_sessions (
    id uuid primary key default gen_random_uuid(),
    scope_id text not null default 'mall' check (scope_id = 'mall'),
    session_key text not null,
    turn_count integer not null default 0,
    last_question_at timestamptz,
    expires_at timestamptz not null default (now() + interval '12 hours'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (scope_id, session_key)
);

create table if not exists public.mall_assistant_usage (
    id bigint generated by default as identity primary key,
    scope_id text not null default 'mall' check (scope_id = 'mall'),
    session_key text,
    response_source text not null check (response_source in ('direct', 'faq', 'cache', 'openai', 'fallback')),
    model text,
    input_tokens integer not null default 0,
    output_tokens integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.mall_assistant_rate_limits (
    scope_id text not null default 'mall' check (scope_id = 'mall'),
    client_hash text not null,
    window_started_at timestamptz not null default now(),
    request_count integer not null default 0,
    updated_at timestamptz not null default now(),
    primary key (scope_id, client_hash)
);

create table if not exists public.mall_assistant_answer_cache (
    scope_id text not null default 'mall' check (scope_id = 'mall'),
    question_hash text not null,
    answer text not null,
    expires_at timestamptz not null default (now() + interval '7 days'),
    created_at timestamptz not null default now(),
    primary key (scope_id, question_hash)
);

-- Mensajes enviados desde el mesón. La escritura pública se hace sólo por RPC.
create table if not exists public.mall_feedback (
    id uuid primary key default gen_random_uuid(),
    session_key text,
    category text not null check (category in ('complaint', 'suggestion')),
    visitor_name text not null,
    email text,
    phone text,
    message text not null,
    consent_at timestamptz not null,
    status text not null default 'new' check (status in ('new', 'reviewing', 'resolved', 'dismissed')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists mall_assistant_sessions_expiry_idx
    on public.mall_assistant_sessions(expires_at);
create index if not exists mall_assistant_usage_created_idx
    on public.mall_assistant_usage(created_at desc);
create index if not exists mall_feedback_created_idx
    on public.mall_feedback(created_at desc);
create index if not exists mall_feedback_status_idx
    on public.mall_feedback(status, created_at desc);

insert into public.mall_assistant_settings (
    id, assistant_id, physical_location, object_key,
    position_x, position_y, position_z, rotation_y,
    enabled, assistant_name, greeting
)
values (
    1, 'main-information-assistant', 'Mesón principal de informaciones', 'information-desk-main',
    -17, 2, 0, 1.5707963267948966,
    true, 'Asistente del Mall', 'Hola. Soy el asistente del Mall Emprendimientos. ¿Qué información necesitas?'
)
on conflict (id) do nothing;

comment on table public.mall_assistant_settings is
    'Registro y entrenamiento del asistente virtual ubicado en el mesón principal de informaciones.';
comment on column public.mall_assistant_settings.object_key is
    'Identificador estable del objeto 3D que representa el mesón de informaciones.';
comment on column public.mall_assistant_settings.position_x is
    'Coordenada X del asistente físico en el mundo 3D.';
comment on column public.mall_assistant_settings.position_y is
    'Coordenada Y aproximada de la cabeza del asistente físico en el mundo 3D.';
comment on column public.mall_assistant_settings.position_z is
    'Coordenada Z del asistente físico en el mundo 3D.';

alter table public.mall_assistant_settings enable row level security;
alter table public.mall_assistant_sessions enable row level security;
alter table public.mall_assistant_usage enable row level security;
alter table public.mall_assistant_rate_limits enable row level security;
alter table public.mall_assistant_answer_cache enable row level security;
alter table public.mall_feedback enable row level security;

drop policy if exists "Public reads enabled mall assistant" on public.mall_assistant_settings;
drop policy if exists "Public reads mall assistant configuration" on public.mall_assistant_settings;
create policy "Public reads mall assistant configuration"
on public.mall_assistant_settings for select
to anon, authenticated
using (true);

drop policy if exists "Admins manage mall assistant" on public.mall_assistant_settings;
create policy "Admins manage mall assistant"
on public.mall_assistant_settings for all
to authenticated
using (public.is_mall_admin())
with check (public.is_mall_admin());

drop policy if exists "Admins read mall feedback" on public.mall_feedback;
create policy "Admins read mall feedback"
on public.mall_feedback for select
to authenticated
using (public.is_mall_admin());

drop policy if exists "Admins update mall feedback" on public.mall_feedback;
create policy "Admins update mall feedback"
on public.mall_feedback for update
to authenticated
using (public.is_mall_admin())
with check (public.is_mall_admin());

-- RPC para recibir reclamos/sugerencias sin permitir INSERT directo a visitantes.
create or replace function public.submit_mall_feedback(
    p_session_key text,
    p_category text,
    p_visitor_name text,
    p_email text,
    p_phone text,
    p_message text,
    p_consent boolean
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
    v_feedback_id uuid;
    v_session_key text;
    v_category text;
    v_name text;
    v_email text;
    v_phone text;
    v_message text;
begin
    if not coalesce(p_consent, false) then
        raise exception 'Debes autorizar el envío de tus datos.';
    end if;

    v_session_key := left(nullif(trim(coalesce(p_session_key, '')), ''), 120);
    v_category := case when p_category in ('complaint', 'suggestion') then p_category else null end;
    v_name := left(trim(coalesce(p_visitor_name, '')), 120);
    v_email := left(nullif(trim(coalesce(p_email, '')), ''), 200);
    v_phone := left(nullif(trim(coalesce(p_phone, '')), ''), 40);
    v_message := left(trim(coalesce(p_message, '')), 2000);

    if v_category is null then raise exception 'Selecciona reclamo o sugerencia.'; end if;
    if length(v_name) < 2 then raise exception 'Ingresa tu nombre.'; end if;
    if length(v_message) < 5 then raise exception 'Escribe un mensaje más detallado.'; end if;

    -- Evita dobles envíos accidentales desde la misma conversación.
    if v_session_key is not null then
        select f.id into v_feedback_id
        from public.mall_feedback f
        where f.session_key = v_session_key
          and f.category = v_category
          and f.message = v_message
          and f.created_at > now() - interval '15 minutes'
        order by f.created_at desc
        limit 1;
        if v_feedback_id is not null then return v_feedback_id; end if;
    end if;

    insert into public.mall_feedback (
        session_key, category, visitor_name, email, phone, message, consent_at
    ) values (
        v_session_key, v_category, v_name, v_email, v_phone, v_message, now()
    ) returning id into v_feedback_id;

    return v_feedback_id;
end;
$$;

revoke all on public.mall_assistant_settings from public;
grant select on public.mall_assistant_settings to anon, authenticated;
grant select, insert, update on public.mall_assistant_settings to authenticated;

revoke all on public.mall_feedback from public;
grant select, update on public.mall_feedback to authenticated;
revoke all on function public.submit_mall_feedback(text, text, text, text, text, text, boolean) from public;
grant execute on function public.submit_mall_feedback(text, text, text, text, text, text, boolean) to anon, authenticated;

commit;
