begin;

create table if not exists public.physical_spaces (
    physical_space_id text primary key,
    kind text not null
        check (kind in ('anchor', 'boutique', 'micro', 'service', 'void', 'other')),
    floor_label text not null,
    axis text,
    quadrant text,
    slot_index integer not null default 0,
    source_code text,
    display_code text,
    x1 numeric(10,2) not null,
    z1 numeric(10,2) not null,
    x2 numeric(10,2) not null,
    z2 numeric(10,2) not null,
    x3 numeric(10,2) not null,
    z3 numeric(10,2) not null,
    x4 numeric(10,2) not null,
    z4 numeric(10,2) not null,
    y1 numeric(10,2) not null,
    y2 numeric(10,2) not null,
    inventory_status text not null default 'unassigned'
        check (inventory_status in ('anchor', 'candidate_store', 'shared_corner', 'reserved', 'inactive', 'merged', 'undefined')),
    inventory_notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint physical_spaces_height_check check (y2 > y1)
);

create index if not exists physical_spaces_kind_idx
on public.physical_spaces (kind);

create index if not exists physical_spaces_floor_label_idx
on public.physical_spaces (floor_label);

create index if not exists physical_spaces_source_code_idx
on public.physical_spaces (source_code);

create index if not exists physical_spaces_display_code_idx
on public.physical_spaces (display_code);

alter table public.physical_spaces enable row level security;

drop policy if exists "Mall admins can manage physical spaces" on public.physical_spaces;
create policy "Mall admins can manage physical spaces"
on public.physical_spaces for all
using (public.is_mall_admin())
with check (public.is_mall_admin());

comment on table public.physical_spaces is 'Catastro maestro de espacios fisicos del mall. Cada espacio es indivisible y no depende del nombre comercial.';
comment on column public.physical_spaces.floor_label is 'Piso o tramo vertical del espacio: 1, 2 o 2-niveles para anclas.';
comment on column public.physical_spaces.inventory_status is 'Estado operativo del espacio fisico antes de asignarlo a un registro comercial.';

create table if not exists public.store_physical_links (
    id bigint generated by default as identity primary key,
    physical_space_id text not null references public.physical_spaces(physical_space_id) on delete cascade,
    store_id text references public.stores(id) on delete cascade,
    relation_type text not null default 'exclusive'
        check (relation_type in ('exclusive', 'shared_front', 'merged', 'legacy_alias', 'reserved')),
    is_primary boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint store_physical_links_unique unique (physical_space_id, store_id)
);

create index if not exists store_physical_links_store_id_idx
on public.store_physical_links (store_id);

alter table public.store_physical_links enable row level security;

drop policy if exists "Mall admins can manage store physical links" on public.store_physical_links;
create policy "Mall admins can manage store physical links"
on public.store_physical_links for all
using (public.is_mall_admin())
with check (public.is_mall_admin());

comment on table public.store_physical_links is 'Relacion entre espacios fisicos del mall y registros comerciales en stores.';

insert into public.physical_spaces (
    physical_space_id, kind, floor_label, axis, quadrant, slot_index,
    source_code, display_code,
    x1, z1, x2, z2, x3, z3, x4, z4,
    y1, y2, inventory_status, inventory_notes
)
values
    ('phys_anchor_e', 'anchor', '2-niveles', 'anchor', 'E', 1, 'E', 'E', -125, 35, -125, -35, -90.95, -35, -90.95, 35, 0, 15, 'anchor', 'Ancla de dos niveles'),
    ('phys_anchor_n', 'anchor', '2-niveles', 'anchor', 'N', 1, 'N', 'N', 35, 125, -35, 125, -35, 90.95, 35, 90.95, 0, 15, 'anchor', 'Ancla de dos niveles'),
    ('phys_anchor_o', 'anchor', '2-niveles', 'anchor', 'O', 1, 'O', 'O', 125, -35, 125, 35, 90.95, 35, 90.95, -35, 0, 15, 'anchor', 'Ancla de dos niveles'),
    ('phys_anchor_s', 'anchor', '2-niveles', 'anchor', 'S', 1, 'S', 'S', -35, -125, 35, -125, 35, -90.95, -35, -90.95, 0, 15, 'anchor', 'Ancla de dos niveles'),
    ('phys_b_f1_xn_zn_horizontal_01', 'boutique', '1', 'horizontal', 'xn_zn', 1, 'S101', 'OS-10', -29, -35, -17, -35, -17, -17, -29, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_horizontal_02', 'boutique', '1', 'horizontal', 'xn_zn', 2, 'S102', 'O-107', -41, -35, -29, -35, -29, -17, -41, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_horizontal_03', 'boutique', '1', 'horizontal', 'xn_zn', 3, 'S103', 'O-105', -53, -35, -41, -35, -41, -17, -53, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_horizontal_04', 'boutique', '1', 'horizontal', 'xn_zn', 4, 'S104', 'O-103', -71, -35, -59, -35, -59, -17, -71, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_horizontal_05', 'boutique', '1', 'horizontal', 'xn_zn', 5, 'S105', 'O-101', -83, -35, -71, -35, -71, -17, -83, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_vertical_01', 'boutique', '1', 'vertical', 'xn_zn', 1, 'E101', 'SE-10', -35, -29, -17, -29, -17, -17, -35, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_vertical_02', 'boutique', '1', 'vertical', 'xn_zn', 2, 'E102', 'S-107', -35, -41, -17, -41, -17, -29, -35, -29, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_vertical_03', 'boutique', '1', 'vertical', 'xn_zn', 3, 'E103', 'S-105', -35, -53, -17, -53, -17, -41, -35, -41, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_vertical_04', 'boutique', '1', 'vertical', 'xn_zn', 4, 'E104', 'S-103', -35, -71, -17, -71, -17, -59, -35, -59, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zn_vertical_05', 'boutique', '1', 'vertical', 'xn_zn', 5, 'E105', 'S-101', -35, -83, -17, -83, -17, -71, -35, -71, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_horizontal_01', 'boutique', '1', 'horizontal', 'xn_zp', 1, 'N101', 'N101', -29, 17, -17, 17, -17, 35, -29, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_horizontal_02', 'boutique', '1', 'horizontal', 'xn_zp', 2, 'N102', 'O-108', -41, 17, -29, 17, -29, 35, -41, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_horizontal_03', 'boutique', '1', 'horizontal', 'xn_zp', 3, 'N103', 'O-106', -53, 17, -41, 17, -41, 35, -53, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_horizontal_04', 'boutique', '1', 'horizontal', 'xn_zp', 4, 'N104', 'O-104', -71, 17, -59, 17, -59, 35, -71, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_horizontal_05', 'boutique', '1', 'horizontal', 'xn_zp', 5, 'N105', 'O-102', -83, 17, -71, 17, -71, 35, -83, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_vertical_01', 'boutique', '1', 'vertical', 'xn_zp', 1, 'E101', 'SE-10', -35, 17, -17, 17, -17, 29, -35, 29, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_vertical_02', 'boutique', '1', 'vertical', 'xn_zp', 2, 'E102', 'S-107', -35, 29, -17, 29, -17, 41, -35, 41, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_vertical_03', 'boutique', '1', 'vertical', 'xn_zp', 3, 'E103', 'S-105', -35, 41, -17, 41, -17, 53, -35, 53, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_vertical_04', 'boutique', '1', 'vertical', 'xn_zp', 4, 'E104', 'S-103', -35, 59, -17, 59, -17, 71, -35, 71, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xn_zp_vertical_05', 'boutique', '1', 'vertical', 'xn_zp', 5, 'E105', 'S-101', -35, 71, -17, 71, -17, 83, -35, 83, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_horizontal_01', 'boutique', '1', 'horizontal', 'xp_zn', 1, 'S101', 'OS-10', 17, -35, 29, -35, 29, -17, 17, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_horizontal_02', 'boutique', '1', 'horizontal', 'xp_zn', 2, 'S102', 'O-107', 29, -35, 41, -35, 41, -17, 29, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_horizontal_03', 'boutique', '1', 'horizontal', 'xp_zn', 3, 'S103', 'O-105', 41, -35, 53, -35, 53, -17, 41, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_horizontal_04', 'boutique', '1', 'horizontal', 'xp_zn', 4, 'S104', 'O-103', 59, -35, 71, -35, 71, -17, 59, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_horizontal_05', 'boutique', '1', 'horizontal', 'xp_zn', 5, 'S105', 'O-101', 71, -35, 83, -35, 83, -17, 71, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_vertical_01', 'boutique', '1', 'vertical', 'xp_zn', 1, 'O101', 'OS-10', 17, -29, 35, -29, 35, -17, 17, -17, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_vertical_02', 'boutique', '1', 'vertical', 'xp_zn', 2, 'O102', 'S-108', 17, -41, 35, -41, 35, -29, 17, -29, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_vertical_03', 'boutique', '1', 'vertical', 'xp_zn', 3, 'O103', 'S-106', 17, -53, 35, -53, 35, -41, 17, -41, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_vertical_04', 'boutique', '1', 'vertical', 'xp_zn', 4, 'O104', 'S-104', 17, -71, 35, -71, 35, -59, 17, -59, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zn_vertical_05', 'boutique', '1', 'vertical', 'xp_zn', 5, 'O105', 'S-102', 17, -83, 35, -83, 35, -71, 17, -71, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_horizontal_01', 'boutique', '1', 'horizontal', 'xp_zp', 1, 'N101', 'N101', 17, 17, 29, 17, 29, 35, 17, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_horizontal_02', 'boutique', '1', 'horizontal', 'xp_zp', 2, 'N102', 'O-108', 29, 17, 41, 17, 41, 35, 29, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_horizontal_03', 'boutique', '1', 'horizontal', 'xp_zp', 3, 'N103', 'O-106', 41, 17, 53, 17, 53, 35, 41, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_horizontal_04', 'boutique', '1', 'horizontal', 'xp_zp', 4, 'N104', 'O-104', 59, 17, 71, 17, 71, 35, 59, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_horizontal_05', 'boutique', '1', 'horizontal', 'xp_zp', 5, 'N105', 'O-102', 71, 17, 83, 17, 83, 35, 71, 35, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_vertical_01', 'boutique', '1', 'vertical', 'xp_zp', 1, 'O101', 'OS-10', 17, 17, 35, 17, 35, 29, 17, 29, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_vertical_02', 'boutique', '1', 'vertical', 'xp_zp', 2, 'O102', 'S-108', 17, 29, 35, 29, 35, 41, 17, 41, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_vertical_03', 'boutique', '1', 'vertical', 'xp_zp', 3, 'O103', 'S-106', 17, 41, 35, 41, 35, 53, 17, 53, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_vertical_04', 'boutique', '1', 'vertical', 'xp_zp', 4, 'O104', 'S-104', 17, 59, 35, 59, 35, 71, 17, 71, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f1_xp_zp_vertical_05', 'boutique', '1', 'vertical', 'xp_zp', 5, 'O105', 'S-102', 17, 71, 35, 71, 35, 83, 17, 83, 0, 5.2, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_01', 'boutique', '2', 'horizontal', 'xn_zn', 1, 'S201', 'S201', -29, -35, -17, -35, -17, -17, -29, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_02', 'boutique', '2', 'horizontal', 'xn_zn', 2, 'S202', 'S202', -41, -35, -29, -35, -29, -17, -41, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_03', 'boutique', '2', 'horizontal', 'xn_zn', 3, 'S203', 'S203', -53, -35, -41, -35, -41, -17, -53, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_04', 'boutique', '2', 'horizontal', 'xn_zn', 4, 'S204', 'S204', -65, -35, -53, -35, -53, -17, -65, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_05', 'boutique', '2', 'horizontal', 'xn_zn', 5, 'S205', 'S205', -77, -35, -65, -35, -65, -17, -77, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_06', 'boutique', '2', 'horizontal', 'xn_zn', 6, 'S206', 'S206', -89, -35, -77, -35, -77, -17, -89, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_horizontal_07', 'boutique', '2', 'horizontal', 'xn_zn', 7, 'S207', 'S207', -95, -35, -83, -35, -83, -17, -95, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_01', 'boutique', '2', 'vertical', 'xn_zn', 1, 'E201', 'E201', -35, -29, -17, -29, -17, -17, -35, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_02', 'boutique', '2', 'vertical', 'xn_zn', 2, 'E202', 'E202', -35, -41, -17, -41, -17, -29, -35, -29, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_03', 'boutique', '2', 'vertical', 'xn_zn', 3, 'E203', 'E203', -35, -53, -17, -53, -17, -41, -35, -41, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_04', 'boutique', '2', 'vertical', 'xn_zn', 4, 'E204', 'E204', -35, -65, -17, -65, -17, -53, -35, -53, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_05', 'boutique', '2', 'vertical', 'xn_zn', 5, 'E205', 'E205', -35, -77, -17, -77, -17, -65, -35, -65, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_06', 'boutique', '2', 'vertical', 'xn_zn', 6, 'E206', 'E206', -35, -89, -17, -89, -17, -77, -35, -77, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zn_vertical_07', 'boutique', '2', 'vertical', 'xn_zn', 7, 'E207', 'E207', -35, -95, -17, -95, -17, -83, -35, -83, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_01', 'boutique', '2', 'horizontal', 'xn_zp', 1, 'N201', 'N201', -29, 17, -17, 17, -17, 35, -29, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_02', 'boutique', '2', 'horizontal', 'xn_zp', 2, 'N202', 'N202', -41, 17, -29, 17, -29, 35, -41, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_03', 'boutique', '2', 'horizontal', 'xn_zp', 3, 'N203', 'N203', -53, 17, -41, 17, -41, 35, -53, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_04', 'boutique', '2', 'horizontal', 'xn_zp', 4, 'N204', 'N204', -65, 17, -53, 17, -53, 35, -65, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_05', 'boutique', '2', 'horizontal', 'xn_zp', 5, 'N205', 'N205', -77, 17, -65, 17, -65, 35, -77, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_06', 'boutique', '2', 'horizontal', 'xn_zp', 6, 'N206', 'N206', -89, 17, -77, 17, -77, 35, -89, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_horizontal_07', 'boutique', '2', 'horizontal', 'xn_zp', 7, 'N207', 'N207', -95, 17, -83, 17, -83, 35, -95, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_01', 'boutique', '2', 'vertical', 'xn_zp', 1, 'E201', 'E201', -35, 17, -17, 17, -17, 29, -35, 29, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_02', 'boutique', '2', 'vertical', 'xn_zp', 2, 'E202', 'E202', -35, 29, -17, 29, -17, 41, -35, 41, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_03', 'boutique', '2', 'vertical', 'xn_zp', 3, 'E203', 'E203', -35, 41, -17, 41, -17, 53, -35, 53, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_04', 'boutique', '2', 'vertical', 'xn_zp', 4, 'E204', 'E204', -35, 53, -17, 53, -17, 65, -35, 65, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_05', 'boutique', '2', 'vertical', 'xn_zp', 5, 'E205', 'E205', -35, 65, -17, 65, -17, 77, -35, 77, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_06', 'boutique', '2', 'vertical', 'xn_zp', 6, 'E206', 'E206', -35, 77, -17, 77, -17, 89, -35, 89, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xn_zp_vertical_07', 'boutique', '2', 'vertical', 'xn_zp', 7, 'E207', 'E207', -35, 83, -17, 83, -17, 95, -35, 95, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_01', 'boutique', '2', 'horizontal', 'xp_zn', 1, 'S201', 'S201', 17, -35, 29, -35, 29, -17, 17, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_02', 'boutique', '2', 'horizontal', 'xp_zn', 2, 'S202', 'S202', 29, -35, 41, -35, 41, -17, 29, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_03', 'boutique', '2', 'horizontal', 'xp_zn', 3, 'S203', 'S203', 41, -35, 53, -35, 53, -17, 41, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_04', 'boutique', '2', 'horizontal', 'xp_zn', 4, 'S204', 'S204', 53, -35, 65, -35, 65, -17, 53, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_05', 'boutique', '2', 'horizontal', 'xp_zn', 5, 'S205', 'S205', 65, -35, 77, -35, 77, -17, 65, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_06', 'boutique', '2', 'horizontal', 'xp_zn', 6, 'S206', 'S206', 77, -35, 89, -35, 89, -17, 77, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_horizontal_07', 'boutique', '2', 'horizontal', 'xp_zn', 7, 'S207', 'S207', 83, -35, 95, -35, 95, -17, 83, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_01', 'boutique', '2', 'vertical', 'xp_zn', 1, 'O201', 'O201', 17, -29, 35, -29, 35, -17, 17, -17, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_02', 'boutique', '2', 'vertical', 'xp_zn', 2, 'O202', 'O202', 17, -41, 35, -41, 35, -29, 17, -29, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_03', 'boutique', '2', 'vertical', 'xp_zn', 3, 'O203', 'O203', 17, -53, 35, -53, 35, -41, 17, -41, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_04', 'boutique', '2', 'vertical', 'xp_zn', 4, 'O204', 'O204', 17, -65, 35, -65, 35, -53, 17, -53, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_05', 'boutique', '2', 'vertical', 'xp_zn', 5, 'O205', 'O205', 17, -77, 35, -77, 35, -65, 17, -65, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_06', 'boutique', '2', 'vertical', 'xp_zn', 6, 'O206', 'O206', 17, -89, 35, -89, 35, -77, 17, -77, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zn_vertical_07', 'boutique', '2', 'vertical', 'xp_zn', 7, 'O207', 'O207', 17, -95, 35, -95, 35, -83, 17, -83, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_01', 'boutique', '2', 'horizontal', 'xp_zp', 1, 'N201', 'N201', 17, 17, 29, 17, 29, 35, 17, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_02', 'boutique', '2', 'horizontal', 'xp_zp', 2, 'N202', 'N202', 29, 17, 41, 17, 41, 35, 29, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_03', 'boutique', '2', 'horizontal', 'xp_zp', 3, 'N203', 'N203', 41, 17, 53, 17, 53, 35, 41, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_04', 'boutique', '2', 'horizontal', 'xp_zp', 4, 'N204', 'N204', 53, 17, 65, 17, 65, 35, 53, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_05', 'boutique', '2', 'horizontal', 'xp_zp', 5, 'N205', 'N205', 65, 17, 77, 17, 77, 35, 65, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_06', 'boutique', '2', 'horizontal', 'xp_zp', 6, 'N206', 'N206', 77, 17, 89, 17, 89, 35, 77, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_horizontal_07', 'boutique', '2', 'horizontal', 'xp_zp', 7, 'N207', 'N207', 83, 17, 95, 17, 95, 35, 83, 35, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_01', 'boutique', '2', 'vertical', 'xp_zp', 1, 'O201', 'O201', 17, 17, 35, 17, 35, 29, 17, 29, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_02', 'boutique', '2', 'vertical', 'xp_zp', 2, 'O202', 'O202', 17, 29, 35, 29, 35, 41, 17, 41, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_03', 'boutique', '2', 'vertical', 'xp_zp', 3, 'O203', 'O203', 17, 41, 35, 41, 35, 53, 17, 53, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_04', 'boutique', '2', 'vertical', 'xp_zp', 4, 'O204', 'O204', 17, 53, 35, 53, 35, 65, 17, 65, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_05', 'boutique', '2', 'vertical', 'xp_zp', 5, 'O205', 'O205', 17, 65, 35, 65, 35, 77, 17, 77, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_06', 'boutique', '2', 'vertical', 'xp_zp', 6, 'O206', 'O206', 17, 77, 35, 77, 35, 89, 17, 89, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria'),
    ('phys_b_f2_xp_zp_vertical_07', 'boutique', '2', 'vertical', 'xp_zp', 7, 'O207', 'O207', 17, 83, 35, 83, 35, 95, 17, 95, 5.5, 10.7, 'candidate_store', 'Espacio tipo local inventariado desde geometria')
on conflict (physical_space_id) do update
set
    kind = excluded.kind,
    floor_label = excluded.floor_label,
    axis = excluded.axis,
    quadrant = excluded.quadrant,
    slot_index = excluded.slot_index,
    source_code = excluded.source_code,
    display_code = excluded.display_code,
    x1 = excluded.x1,
    z1 = excluded.z1,
    x2 = excluded.x2,
    z2 = excluded.z2,
    x3 = excluded.x3,
    z3 = excluded.z3,
    x4 = excluded.x4,
    z4 = excluded.z4,
    y1 = excluded.y1,
    y2 = excluded.y2,
    inventory_status = excluded.inventory_status,
    inventory_notes = excluded.inventory_notes,
    updated_at = now();

commit;
