begin;

create table if not exists public.store_bot_settings (
    store_id text primary key references public.stores(id) on delete cascade,
    enabled boolean not null default false,
    assistant_name text not null default 'Asistente',
    greeting text not null default 'Hola. Bienvenido a nuestra tienda. ¿En qué puedo ayudarte?',
    store_brief text not null default '',
    handoff_message text not null default 'Veo que tienes varias preguntas y quiero que recibas una respuesta completa. Si gustas, déjame tu nombre y un medio de contacto. Enviaré tu consulta a la persona encargada de la tienda, quien estará encantada de responderte personalmente.',
    faq jsonb not null default '[]'::jsonb,
    max_turns integer not null default 4 check (max_turns between 1 and 6),
    question_max_chars integer not null default 300 check (question_max_chars between 80 and 500),
    answer_max_words integer not null default 80 check (answer_max_words between 30 and 120),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.store_bot_settings
    add column if not exists store_brief text not null default '';

create table if not exists public.store_bot_sessions (
    id uuid primary key default gen_random_uuid(),
    store_id text not null references public.stores(id) on delete cascade,
    session_key text not null,
    turn_count integer not null default 0,
    last_question_at timestamptz,
    expires_at timestamptz not null default (now() + interval '12 hours'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (store_id, session_key)
);

create table if not exists public.store_bot_leads (
    id uuid primary key default gen_random_uuid(),
    store_id text not null references public.stores(id) on delete cascade,
    session_key text,
    visitor_name text not null,
    email text,
    phone text,
    contact_preference text not null default 'email' check (contact_preference in ('email', 'whatsapp', 'cualquiera')),
    question_summary text,
    consent_at timestamptz not null,
    status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
    created_at timestamptz not null default now()
);

create table if not exists public.store_bot_usage (
    id bigint generated by default as identity primary key,
    store_id text not null references public.stores(id) on delete cascade,
    session_key text,
    response_source text not null check (response_source in ('direct', 'faq', 'cache', 'openai', 'fallback')),
    model text,
    input_tokens integer not null default 0,
    output_tokens integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.store_bot_rate_limits (
    store_id text not null references public.stores(id) on delete cascade,
    client_hash text not null,
    window_started_at timestamptz not null default now(),
    request_count integer not null default 0,
    updated_at timestamptz not null default now(),
    primary key (store_id, client_hash)
);

create table if not exists public.store_bot_answer_cache (
    store_id text not null references public.stores(id) on delete cascade,
    question_hash text not null,
    answer text not null,
    expires_at timestamptz not null default (now() + interval '7 days'),
    created_at timestamptz not null default now(),
    primary key (store_id, question_hash)
);

create index if not exists store_bot_leads_store_created_idx on public.store_bot_leads(store_id, created_at desc);
create unique index if not exists store_bot_leads_store_session_uidx on public.store_bot_leads(store_id, session_key) where session_key is not null;
create index if not exists store_bot_usage_store_created_idx on public.store_bot_usage(store_id, created_at desc);
create index if not exists store_bot_sessions_expiry_idx on public.store_bot_sessions(expires_at);

alter table public.store_bot_settings enable row level security;
alter table public.store_bot_sessions enable row level security;
alter table public.store_bot_leads enable row level security;
alter table public.store_bot_usage enable row level security;
alter table public.store_bot_rate_limits enable row level security;
alter table public.store_bot_answer_cache enable row level security;

drop policy if exists "Public reads enabled store bots" on public.store_bot_settings;
create policy "Public reads enabled store bots"
on public.store_bot_settings for select
to anon, authenticated
using (
    enabled
    or public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_settings.store_id and s.owner_id = auth.uid()
    )
);

drop policy if exists "Owners manage store bots" on public.store_bot_settings;
create policy "Owners manage store bots"
on public.store_bot_settings for all
to authenticated
using (
    public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_settings.store_id and s.owner_id = auth.uid()
    )
)
with check (
    public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_settings.store_id and s.owner_id = auth.uid()
    )
);

drop policy if exists "Owners read store bot leads" on public.store_bot_leads;
create policy "Owners read store bot leads"
on public.store_bot_leads for select
to authenticated
using (
    public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_leads.store_id and s.owner_id = auth.uid()
    )
);

drop policy if exists "Owners update store bot leads" on public.store_bot_leads;
create policy "Owners update store bot leads"
on public.store_bot_leads for update
to authenticated
using (
    public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_leads.store_id and s.owner_id = auth.uid()
    )
)
with check (
    public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_leads.store_id and s.owner_id = auth.uid()
    )
);

drop policy if exists "Owners read store bot usage" on public.store_bot_usage;
create policy "Owners read store bot usage"
on public.store_bot_usage for select
to authenticated
using (
    public.is_mall_admin()
    or exists (
        select 1 from public.stores s
        where s.id = store_bot_usage.store_id and s.owner_id = auth.uid()
    )
);

create or replace function public.submit_store_bot_lead(
    p_store_code text,
    p_session_key text,
    p_visitor_name text,
    p_email text,
    p_phone text,
    p_contact_preference text,
    p_question_summary text,
    p_consent boolean
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
    v_store_id text;
    v_lead_id uuid;
begin
    if not coalesce(p_consent, false) then
        raise exception 'Debes autorizar el envío de tus datos.';
    end if;
    if length(trim(coalesce(p_visitor_name, ''))) < 2 then
        raise exception 'Ingresa tu nombre.';
    end if;
    if nullif(trim(coalesce(p_email, '')), '') is null and nullif(trim(coalesce(p_phone, '')), '') is null then
        raise exception 'Ingresa un correo o WhatsApp.';
    end if;

    select s.id into v_store_id
    from public.stores s
    where lower(s.id) = lower(trim(p_store_code))
       or lower(s.local_code) = lower(trim(p_store_code))
    order by case when lower(s.local_code) = lower(trim(p_store_code)) then 0 else 1 end
    limit 1;

    if v_store_id is null then raise exception 'Local no encontrado.'; end if;

    select l.id into v_lead_id
    from public.store_bot_leads l
    where l.store_id = v_store_id
      and (
          (nullif(trim(coalesce(p_session_key, '')), '') is not null and l.session_key = left(trim(p_session_key), 120))
          or (nullif(trim(coalesce(p_email, '')), '') is not null and lower(l.email) = lower(trim(p_email)))
          or (nullif(trim(coalesce(p_phone, '')), '') is not null and l.phone = trim(p_phone))
      )
      and l.created_at > now() - interval '30 minutes'
    order by l.created_at desc
    limit 1;
    if v_lead_id is not null then return v_lead_id; end if;

    insert into public.store_bot_leads (
        store_id, session_key, visitor_name, email, phone,
        contact_preference, question_summary, consent_at
    ) values (
        v_store_id,
        left(nullif(trim(coalesce(p_session_key, '')), ''), 120),
        left(trim(p_visitor_name), 120),
        left(nullif(trim(coalesce(p_email, '')), ''), 200),
        left(nullif(trim(coalesce(p_phone, '')), ''), 40),
        case when p_contact_preference in ('email', 'whatsapp', 'cualquiera') then p_contact_preference else 'cualquiera' end,
        left(nullif(trim(coalesce(p_question_summary, '')), ''), 1000),
        now()
    ) returning id into v_lead_id;

    return v_lead_id;
end;
$$;

grant select on public.store_bot_settings to anon, authenticated;
grant select, insert, update on public.store_bot_settings to authenticated;
grant select, update on public.store_bot_leads to authenticated;
grant select on public.store_bot_usage to authenticated;
grant execute on function public.submit_store_bot_lead(text, text, text, text, text, text, text, boolean) to anon, authenticated;

insert into public.store_bot_settings (store_id, enabled, assistant_name, greeting)
select
    s.id,
    true,
    case when upper(s.local_code) = 'E-105' then 'Isabella' else 'Asistente AM' end,
    case
        when upper(s.local_code) = 'E-105' then 'Hola, soy Isabella. Bienvenido a Isabella Joyas. ¿En qué puedo ayudarte?'
        else 'Hola, soy el asistente de AM Store. ¿En qué puedo ayudarte?'
    end
from public.stores s
where upper(s.local_code) in ('SE-10', 'E-105')
  and s.owner_id is not null
on conflict (store_id) do nothing;

commit;
