const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..', '..');
const read = (relativePath) => fs.readFileSync(path.join(projectRoot, relativePath), 'utf8');

const assistant = read('js/mall/mall-store-assistant.js');
const world = read('js/mall/mall-world.js');
const ui = read('js/mall/mall-ui.js');
const html = read('index.html');
const migration = read('supabase/mall_information_assistant_20260830.sql');
const multimallMigration = read('supabase/multimall_phase7_assistant_scope_20260909.sql');
const multimallVerification = read('supabase/multimall_phase7_assistant_verify_20260909.sql');
const edge = read('supabase/functions/store-attendant/index.ts');

assert.match(assistant, /window\.openMallAssistant = async function/);
assert.match(assistant, /mall_assistant_settings/);
assert.match(assistant, /submit_mall_feedback/);
assert.match(assistant, /window\.saveAdminMallAssistantSettings = async function/);
assert.match(world, /isMallInformationAssistant: true/);
assert.match(world, /physicalRegistrationId: 'information-desk-main'/);
assert.match(world, /MALL_INFORMATION_ASSISTANT_AVATAR_URL = ['"]assets\/avatars\/mall-avatar-v1\.glb['"]/);
assert.match(world, /loadMallInformationAssistantAvatar\(assistant, assistantFallback\)/);
assert.match(world, /fallback\.visible = false/);
assert.match(world, /new THREE\.AnimationMixer\(avatar\)/);
assert.match(ui, /window\.openMallAssistant\?\.\(\)/);
assert.match(html, /id="admin-mall-assistant-brief"/);
assert.match(html, /id="mall-feedback-form"/);
assert.match(migration, /create table if not exists public\.mall_assistant_settings/);
assert.match(migration, /object_key text not null default 'information-desk-main'/);
assert.match(migration, /create table if not exists public\.mall_feedback/);
assert.match(migration, /create policy "Admins read mall feedback"/);
assert.match(migration, /grant execute on function public\.submit_mall_feedback/);
assert.match(migration, /revoke all on public\.mall_feedback from public/);
assert.match(edge, /body\?\.scope === "mall"/);
assert.match(edge, /action === "mall_message"/);
assert.match(edge, /settings\.mall_brief/);
assert.match(edge, /https:\/\/api\.openai\.com\/v1\/responses/);
assert.match(edge, /mall_assistant_usage/);
assert.match(multimallMigration, /mall_assistant_settings[\s\S]*primary key \(mall_id, id\)/i);
assert.match(multimallMigration, /submit_mall_feedback\(\s*p_mall_id uuid/i);
assert.match(assistant, /p_mall_id:\s*window\.mallContext\?\.id/i);
assert.match(edge, /mall_assistant_settings[\s\S]*eq\("mall_id", mallId\)/i);
assert.match(edge, /mall:\$\{mallId\}/i);
assert.match(multimallVerification, /rows_without_mall/i);
assert.match(multimallVerification, /table_constraints/i);
assert.match(multimallVerification, /submit_mall_feedback/i);

console.log('Mall information assistant is wired to the physical desk, admin training, and protected feedback storage.');
